
spring.application.name=jdbctemplate
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.sql.init.mode=never


spring.datasource.postgres.jdbc.jdbc-url=jdbc:postgresql://localhost:5432/JdbcEmp
spring.datasource.postgres.jdbc.username=postgres
spring.datasource.postgres.jdbc.password=${POSTGRES_PASSWORD}
spring.datasource.postgres.jdbc.driver-class-name=org.postgresql.Driver


spring.datasource.mysql.jdbc.jdbc-url=jdbc:mysql://localhost:3306/emp_db
spring.datasource.mysql.jdbc.username=root
spring.datasource.mysql.jdbc.password=${MYSQL_PASSWORD}
spring.datasource.mysql.jdbc.driver-class-name=com.mysql.cj.jdbc.Driver