spring.application.name=jdbctemplate
spring.datasource.url=jdbc:postgresql://localhost:5432/JdbcEmp
spring.datasource.username=postgres
spring.datasource.password=mohit@99

spring.datasource.postgres.driver-class-name=org.postgresql.Driver