
spring.application.name=jdbctemplate

spring.datasource.postgres.url=jdbc:postgresql://localhost:5432/JdbcEmp
spring.datasource.postgres.username=postgres
spring.datasource.postgres.password=${POSTGRES_PASSWORD}


spring.datasource.mysql.url=jdbc:mysql://localhost:3306/emp_db
spring.datasource.mysql.username=root
spring.datasource.mysql.password=${MYSQL_PASSWORD}

spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.postgres.driver-class-name=org.postgresql.Driver